// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvrpziszlkufebzqcdsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2cnB6aXN6bGt1ZmVienFjZHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjQ3MjIsImV4cCI6MjA2NzgwMDcyMn0.Uh7CBvA9uRvGJJZAbnQ9FvbdYF6Vtww-o2VA2oTXueY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});